### ISSUE TITLE
會員系統CRUD

### ISSUE THREAD

**Issue by tw30006** [astrocamp/16th-EngiLink#2]
## Users

- 註冊(Create):
    - 信箱, 使用者名稱, 密碼
- 資料瀏覽(Read):
    - 姓名, 生日, 信箱, 性別, 電話, 使用者名稱, 密碼, 照片
- 資料修改(Update):
    - 姓名, 照片, 生日, 信箱, 性別, 電話, 密碼
- 資料刪除(Delete):
    - 不給刪

**Comment by b89k57w62** [comment]
done!!!!!
