### ISSUE TITLE
履歷CRUD

### ISSUE THREAD

**Issue by tw30006** [astrocamp/16th-EngiLink#4]

**Comment by ula0218** [comment]
<img width="980" alt="截圖 2024-05-01 14 55 14" src="https://github.com/astrocamp/16th-EngiLink/assets/157874138/d0cd5de2-8f27-47d7-b029-d514b5ae13c8">

**新增(Create)**

1. 個人基本資料

- 性別
- 生日
- 電子信箱
- 手機
- 地址
- 技能
- 個人網站
- 工作經驗
- Linkedin
- GitHub

2. 教育經驗

- 學校名稱
- 專業
- 學位
- 入學時間
- 畢業時間

3. 工作經驗

- 工作名稱
- 職稱
- 入職時間
- 離職時間
- 是否在職

4. 專案內容

- 專案名稱
- 負責部分
- 技術使用
- 敘述

**瀏覽(Read)**

1. 個人基本資料

- 性別
- 生日
- 電子信箱
- 手機
- 地址
- 技能
- 個人網站
- 工作經驗
- Linkedin
- GitHub

2. 教育經驗

- 學校名稱
- 專業
- 學位
- 入學時間
- 畢業時間

3. 工作經驗

- 工作名稱
- 職稱
- 入職時間
- 離職時間
- 是否在職

4. 專案內容

- 專案名稱
- 負責部分
- 技術使用
- 敘述


**修改(Update)**

1. 個人基本資料

- 性別
- 生日
- 電子信箱
- 手機
- 地址
- 技能
- 個人網站
- 工作經驗
- Linkedin
- GitHub

2. 教育經驗

- 學校名稱
- 專業
- 學位
- 入學時間
- 畢業時間

3. 工作經驗

- 工作名稱
- 職稱
- 入職時間
- 離職時間
- 是否在職

4. 專案內容

- 專案名稱
- 負責部分
- 技術使用
- 敘述


**刪除(Delete)**

[整份履歷可軟刪除]



補充：教育經驗、工作經驗和專案和履歷為多對多關係，後續分票會再處理細節
