### ISSUE TITLE
修正公司的 navbar 顏色不一

### ISSUE THREAD

**Issue by andyhuangdev** [astrocamp/16th-EngiLink#529]
<img width="1728" alt="Screenshot 2024-06-09 at 12 18 37 PM" src="https://github.com/astrocamp/16th-EngiLink/assets/165141963/0692a5bd-9156-40c6-9bdd-7577e644df13">

<img width="1728" alt="Screenshot 2024-06-09 at 12 23 34 PM" src="https://github.com/astrocamp/16th-EngiLink/assets/165141963/6a712fbf-61b7-48af-9648-5c547f186446">

**Comment by tw30006** [comment]
這我昨天有修好，最新dev長這樣，還是你的不是？

<img width="1465" alt="截圖 2024-06-09 中午12 27 11" src="https://github.com/astrocamp/16th-EngiLink/assets/144601116/a3e3c596-8968-4ebd-85d5-7dd177cfcdf3">

**Comment by tw30006** [comment]
第一張沒修到，我立馬修!!
