### ISSUE TITLE
手機履歷專案欄位清單跑版

### ISSUE THREAD

**Issue by b89k57w62** [astrocamp/16th-EngiLink#539]
<img width="375" alt="截圖 2024-06-09 下午1 19 50" src="https://github.com/astrocamp/16th-EngiLink/assets/111471602/bf4a933f-52ac-49d2-8912-d5983837f2be">

**Comment by ula0218** [comment]
樣式統一後，目前最新dev顯示正常
<img width="466" alt="截圖 2024-06-10 12 18 43" src="https://github.com/astrocamp/16th-EngiLink/assets/157874138/e2324803-f322-4686-b0c2-5b709de9d76c">
